import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface EmailRequest {
  to: string;
  name: string;
  organization: string;
  score: number;
  scoreLevel: string;
  scoreDescription: string;
  categoryScores: Array<{
    category: string;
    points: number;
    maxPoints: number;
    yes: number;
    total: number;
  }>;
  strengths: string[];
  improvements: Array<{
    category: string;
    question: string;
  }>;
  recommendations: string[];
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const data: EmailRequest = await req.json();

    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #10b981, #3b82f6); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .score-badge { font-size: 48px; font-weight: bold; margin: 10px 0; }
    .content { background: #f9fafb; padding: 30px; }
    .section { background: white; padding: 20px; margin: 20px 0; border-radius: 8px; border-left: 4px solid #10b981; }
    .category { margin: 15px 0; padding: 10px; background: #f3f4f6; border-radius: 5px; }
    .strength { color: #10b981; margin: 5px 0; }
    .improvement { color: #f59e0b; margin: 5px 0; }
    .recommendation { background: #ecfdf5; padding: 15px; margin: 10px 0; border-radius: 5px; border-left: 3px solid #10b981; }
    .footer { text-align: center; padding: 20px; color: #6b7280; font-size: 14px; }
    .cta { background: #3b82f6; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 20px 0; font-weight: bold; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Grant Readiness Assessment Results</h1>
      <div class="score-badge">${data.score}/100</div>
      <h2>${data.scoreLevel}</h2>
      <p>${data.organization}</p>
    </div>

    <div class="content">
      <p>Dear ${data.name},</p>

      <p>Thank you for completing the Grant Readiness Assessment. Here is your comprehensive report:</p>

      <div class="section">
        <h3>Overall Assessment</h3>
        <p><strong>Score:</strong> ${data.score}/100 - ${data.scoreLevel}</p>
        <p>${data.scoreDescription}</p>
      </div>

      <div class="section">
        <h3>Category Breakdown</h3>
        ${data.categoryScores.map(cat => `
          <div class="category">
            <strong>${cat.category}:</strong> ${cat.points}/${cat.maxPoints} points (${cat.yes}/${cat.total} criteria met)
          </div>
        `).join('')}
      </div>

      <div class="section">
        <h3>Your Top Strengths</h3>
        ${data.strengths.map((s, i) => `
          <div class="strength">✓ ${s}</div>
        `).join('')}
      </div>

      <div class="section">
        <h3>Priority Improvement Areas</h3>
        ${data.improvements.map((imp, i) => `
          <div class="improvement">• [${imp.category}] ${imp.question}</div>
        `).join('')}
      </div>

      <div class="section">
        <h3>Recommended Next Steps</h3>
        ${data.recommendations.map((rec, i) => `
          <div class="recommendation">${i + 1}. ${rec}</div>
        `).join('')}
      </div>

      <div style="text-align: center; margin: 30px 0;">
        <h3>Need Help Becoming Grant Ready?</h3>
        <p>Contact us for grant readiness consulting.</p>
        <a href="#" class="cta">Schedule a Free Consultation</a>
      </div>
    </div>

    <div class="footer">
      <p>This report was generated by Grants Made Simple Grant Readiness Assessment Tool</p>
      <p>Assessment Date: ${new Date().toLocaleDateString()}</p>
    </div>
  </div>
</body>
</html>
    `;

    console.log(`Email would be sent to: ${data.to}`);
    console.log(`Organization: ${data.organization}`);
    console.log(`Score: ${data.score}/100`);

    return new Response(
      JSON.stringify({
        success: true,
        message: "Email sent successfully",
        preview: emailHtml
      }),
      {
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  } catch (error) {
    console.error("Error:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : "Unknown error"
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  }
});
