import { CheckCircle2, AlertCircle, Award } from 'lucide-react';

interface ShareableCardProps {
  organization: string;
  score: number;
  scoreLevel: string;
  scoreColor: string;
  strengths: string[];
  improvements: { category: string; question: string }[];
}

export default function ShareableCard({ organization, score, scoreLevel, scoreColor, strengths, improvements }: ShareableCardProps) {
  const topStrengths = strengths.slice(0, 3);
  const topImprovements = improvements.slice(0, 3);

  return (
    <div id="shareable-card" className="bg-white rounded-2xl shadow-2xl p-8 max-w-2xl mx-auto border-2 border-slate-200">
      <div className="text-center mb-8 pb-6 border-b-2 border-slate-100">
        <div className="bg-gradient-to-r from-emerald-50 to-blue-50 rounded-xl p-6 mb-4">
          <Award className="w-12 h-12 text-blue-600 mx-auto mb-3" />
          <h2 className="text-3xl font-bold text-slate-900 mb-2">
            Grant Readiness Assessment
          </h2>
          <p className="text-xl font-semibold text-slate-700">{organization}</p>
        </div>

        <div className="relative inline-block mb-4">
          <svg className="w-40 h-40 transform -rotate-90">
            <circle
              cx="80"
              cy="80"
              r="70"
              stroke="#e2e8f0"
              strokeWidth="12"
              fill="none"
            />
            <circle
              cx="80"
              cy="80"
              r="70"
              stroke={`${scoreColor === 'emerald' ? '#10b981' : scoreColor === 'amber' ? '#f59e0b' : '#ef4444'}`}
              strokeWidth="12"
              fill="none"
              strokeDasharray={`${2 * Math.PI * 70}`}
              strokeDashoffset={`${2 * Math.PI * 70 * (1 - score / 100)}`}
              strokeLinecap="round"
            />
          </svg>
          <div className="absolute inset-0 flex items-center justify-center">
            <div>
              <div className="text-5xl font-bold text-slate-900">{score}</div>
              <div className="text-xs text-slate-600">out of 100</div>
            </div>
          </div>
        </div>

        <h3 className={`text-2xl font-bold mb-2 ${scoreColor === 'emerald' ? 'text-emerald-600' : scoreColor === 'amber' ? 'text-amber-600' : 'text-red-600'}`}>
          {scoreLevel}
        </h3>
        <p className="text-sm text-slate-500">Assessment Date: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <h4 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-600" />
            Top Strengths
          </h4>
          <ul className="space-y-2">
            {topStrengths.map((strength, index) => (
              <li key={index} className="flex items-start gap-2 text-sm">
                <div className="bg-emerald-100 rounded-full p-1 mt-0.5 flex-shrink-0">
                  <div className="w-4 h-4 flex items-center justify-center text-emerald-700 font-bold text-xs">
                    {index + 1}
                  </div>
                </div>
                <span className="text-slate-700 leading-tight">{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h4 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-amber-600" />
            Priority Improvements
          </h4>
          <ul className="space-y-2">
            {topImprovements.map((item, index) => (
              <li key={index} className="flex items-start gap-2 text-sm">
                <div className="bg-amber-100 rounded-full p-1 mt-0.5 flex-shrink-0">
                  <div className="w-4 h-4 flex items-center justify-center text-amber-700 font-bold text-xs">
                    {index + 1}
                  </div>
                </div>
                <span className="text-slate-700 leading-tight">{item.question}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mt-6 pt-6 border-t-2 border-slate-100 text-center">
        <p className="text-xs text-slate-500">
          Generated by Grants Made Simple Grant Readiness Assessment Tool
        </p>
      </div>
    </div>
  );
}
